import type { Review } from "./types";

const severityLabel: Record<string, string> = {
  info: "Info",
  minor: "Minor",
  major: "Major",
  critical: "Critical",
};

function formatDuration(createdAt: string, finishedAt?: string): string | null {
  if (!finishedAt) return null;
  const ms = new Date(finishedAt).getTime() - new Date(createdAt).getTime();
  if (ms < 1000) return `${ms}ms`;
  const seconds = ms / 1000;
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  return `${(seconds / 60).toFixed(1)}m`;
}

export interface BuiltReviewPdf {
  blob: Blob;
  filename: string;
}

// jsPDF/autotable are loaded on demand — most History page visits never
// trigger an export, so there's no reason to ship them in the main bundle.
export async function buildReviewPdf(review: Review): Promise<BuiltReviewPdf> {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 40;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 50;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Codessa Review Report", marginX, y);
  y += 24;

  doc.setDrawColor(210);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 24;

  const fields: [string, string][] = [
    ["Repository", review.repositoryFullName],
    ["Pull Request", `#${review.pullNumber}`],
    ["Commit", `${review.shortSha} — ${review.commitMessage}`],
    ["Status", review.status],
  ];
  if (review.status === "success" && review.verdict) {
    fields.push(["Verdict", review.verdict.replace(/_/g, " ")]);
  }
  fields.push(
    ["Changes", `+${review.additions} / -${review.deletions}`],
    ["Reviewed at", new Date(review.createdAt).toLocaleString()],
  );
  const duration = formatDuration(review.createdAt, review.finishedAt);
  if (duration) fields.push(["Review duration", duration]);

  doc.setFontSize(10);
  fields.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, marginX, y);
    doc.setFont("helvetica", "normal");
    const wrapped = doc.splitTextToSize(value, pageWidth - marginX * 2 - 120);
    doc.text(wrapped, marginX + 120, y);
    y += 15 * wrapped.length;
  });

  y += 10;

  if (review.summary) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Summary", marginX, y);
    y += 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const wrapped = doc.splitTextToSize(review.summary, pageWidth - marginX * 2);
    doc.text(wrapped, marginX, y);
    y += 15 * wrapped.length + 14;
  }

  if (review.errorMessage) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(185, 28, 28);
    doc.setFontSize(12);
    doc.text("Error", marginX, y);
    y += 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const wrapped = doc.splitTextToSize(review.errorMessage, pageWidth - marginX * 2);
    doc.text(wrapped, marginX, y);
    doc.setTextColor(0, 0, 0);
    y += 15 * wrapped.length + 14;
  }

  if (review.comments.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`Review Comments (${review.comments.length})`, marginX, y);
    y += 10;

    autoTable(doc, {
      startY: y,
      head: [["File", "Line", "Source", "Severity", "Comment", "Vulnerability"]],
      body: review.comments.map((c) => {
        const vulnParts: string[] = [];
        if (c.cwe) vulnParts.push(`${c.cwe.id} — ${c.cwe.name}`);
        if (c.cvss) vulnParts.push(`CVSS ${c.cvss.score.toFixed(1)} (${c.cvss.vector})`);
        if (c.vulnerabilityId) {
          vulnParts.push(`${c.vulnerabilityId} — https://osv.dev/vulnerability/${c.vulnerabilityId}`);
        }
        return [
          c.filePath,
          String(c.line),
          c.source === "sca" ? "Dependency Scan" : "AI",
          severityLabel[c.severity] ?? c.severity,
          c.comment,
          vulnParts.join("\n") || "—",
        ];
      }),
      styles: { fontSize: 9, cellPadding: 6, valign: "top" },
      headStyles: { fillColor: [99, 14, 212], textColor: 255 },
      columnStyles: {
        0: { cellWidth: 90 },
        1: { cellWidth: 30 },
        2: { cellWidth: 55 },
        3: { cellWidth: 45 },
        4: { cellWidth: 130 },
      },
      margin: { left: marginX, right: marginX },
    });
  }

  const pageCount = doc.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(
      `Generated by Codessa · ${new Date().toLocaleString()} · Page ${i} of ${pageCount}`,
      marginX,
      pageHeight - 24,
    );
  }

  const fileSafeRepo = review.repositoryName.replace(/[^a-z0-9-_]/gi, "-");
  const filename = `codessa-review-${fileSafeRepo}-pr${review.pullNumber}-${review.shortSha}.pdf`;

  return { blob: doc.output("blob"), filename };
}
